"""empty message

Revision ID: c1413a420c8e
Revises: 11d0673caacc
Create Date: 2024-06-15 06:07:23.195578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1413a420c8e'
down_revision = '11d0673caacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avater', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_me')
        batch_op.drop_column('avater')

    # ### end Alembic commands ###
